server:
    # 端口号
    port: 8083
spring:
  application:
    # 项目名称
    name: spring-configservice
  cloud:
    config:
      server:
        git:
          url: https://github.com/IBeliveDream/spring-cloud-config-server.git
          username: 1220298776@qq.com
          password: wangjin2333

logging:
  level:
    # 显示日志级别
#    com.springboot.provide.consumer.controller.IHelloControllerFeign: debug
    # 取消注册中心定时回复日志显示（info级别）
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN

